module.exports = Object.freeze({
  AUTHORIZATION_HEADER: "Authorization",
  BASIC: "Basic",
  BEARER: "Bearer",
  GRANT_TYPE: "grant_type",
  CREDENTIALS: "credentials",
  TOKEN: "token",
  ACCESS_TOKEN: "access_token",
  REFRESH_TOKEN: "refresh_token",
  EMAIL: "email",
  PASSWORD: "password",
  EXPIRED: "Expired",
  EXPIRE: "expire",
  BASE64: "base64",
  EMAIL_KEY: "Email",
});
